name: Deploy Custom Application
on:
    push:
      branches:
        - main
jobs:
    deploy: 
      runs-on: ubuntu-latest
      steps:
        
        - name: Checkout Repo
          uses: actions/checkout@v3

        - name: deploy
          run : |
            ssh -o StrictHostKeyChecking=no ubuntu@54.227.126.50 << 'EOF'
            cd /var/www/app
            git pull origin main
            npm install
            npm run build
            cp -R dist/* /var/www/html 
            systemctl restart nginx
            EOF
